import type { CSSProperties } from 'react';
import type { Theme } from '../../theme.config';

export const getFlagToolbarStyles = (theme: Theme): Record<string, CSSProperties> => ({
  toolbar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '20px',
    gap: '16px',
    flexWrap: 'wrap',
  },
  searchWrapper: {
    flex: 1,
    maxWidth: '500px',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  searchContainer: {
    position: 'relative',
    width: '100%',
  },
  searchIcon: {
    position: 'absolute',
    left: '12px',
    top: '50%',
    transform: 'translateY(-50%)',
    display: 'flex',
    alignItems: 'center',
    pointerEvents: 'none',
    zIndex: 1,
  },
  search: {
    width: '100%',
    padding: '10px 40px 10px 40px',
    borderRadius: theme.radius.md,
    border: `1px solid ${theme.colors.borderColor}`,
    backgroundColor: theme.colors.bgCard,
    color: theme.colors.textPrimary,
    fontSize: '14px',
    outline: 'none',
    transition: 'all 0.2s ease',
  },
  clearButton: {
    position: 'absolute',
    right: '10px',
    top: '50%',
    transform: 'translateY(-50%)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '24px',
    height: '24px',
    padding: 0,
    border: 'none',
    borderRadius: theme.radius.sm,
    backgroundColor: 'transparent',
    color: theme.colors.textMuted,
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    zIndex: 1,
  },
  resultCount: {
    fontSize: '12px',
    color: theme.colors.textMuted,
    paddingLeft: '4px',
  },
  createButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '12px 24px',
    borderRadius: theme.radius.md,
    border: 'none',
    backgroundColor: theme.colors.accentPrimary,
    color: theme.name === 'dark' ? theme.colors.bgPrimary : theme.colors.bgSecondary,
    fontWeight: 600,
    cursor: 'pointer',
    fontSize: '14px',
    transition: 'all 0.2s cubic-bezier(0.23, 1, 0.32, 1)',
    whiteSpace: 'nowrap',
    flexShrink: 0,
    boxShadow: theme.shadows.sm,
  },
  createButtonHover: {
    backgroundColor: theme.colors.accentHover,
    transform: 'translateY(-1px)',
    boxShadow: theme.shadows.md,
  },
  actions: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    flexShrink: 0,
  },
  filterSort: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
});
