import type { CSSProperties } from 'react';
import type { Theme } from '../../theme.config';

export const getSortButtonStyles = (theme: Theme): Record<string, CSSProperties> => ({
  container: {
    position: 'relative',
    display: 'inline-block',
  },
  button: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '10px 16px',
    borderRadius: theme.radius.md,
    border: `1px solid ${theme.colors.borderColor}`,
    backgroundColor: theme.colors.bgCard,
    color: theme.colors.textSecondary,
    fontSize: '14px',
    fontWeight: 500,
    cursor: 'pointer',
    transition: 'all 0.2s cubic-bezier(0.23, 1, 0.32, 1)',
    whiteSpace: 'nowrap',
    outline: 'none',
  },
  buttonHover: {
    backgroundColor: theme.colors.accentLight,
    color: theme.colors.textPrimary,
    borderColor: theme.colors.accentPrimary,
    transform: 'translateY(-1px)',
    boxShadow: theme.shadows.sm,
  },
  buttonActive: {
    backgroundColor: theme.colors.accentLight,
    color: theme.colors.textPrimary,
    borderColor: theme.colors.accentPrimary,
  },
  overlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 999,
  },
  dropdown: {
    position: 'absolute',
    top: '100%',
    left: 0,
    right: 0,
    marginTop: '4px',
    backgroundColor: theme.colors.bgCard,
    border: `1px solid ${theme.colors.borderColor}`,
    borderRadius: theme.radius.md,
    boxShadow: theme.shadows.lg,
    zIndex: 1000,
    overflow: 'hidden',
    minWidth: '180px',
  },
  option: {
    display: 'block',
    width: '100%',
    padding: '12px 16px',
    border: 'none',
    backgroundColor: 'transparent',
    color: theme.colors.textSecondary,
    fontSize: '14px',
    textAlign: 'left',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
    ':hover': {
      backgroundColor: theme.colors.accentLight,
      color: theme.colors.textPrimary,
    },
  },
  optionActive: {
    backgroundColor: theme.colors.accentLight,
    color: theme.colors.accentPrimary,
    fontWeight: 600,
  },
});