import type { CSSProperties } from 'react';
import type { Theme } from '../../theme.config';

export const getFilterButtonStyles = (theme: Theme): Record<string, CSSProperties> => ({
  container: {
    position: 'relative',
    display: 'inline-block',
  },
  button: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '10px 16px',
    borderRadius: theme.radius.md,
    border: `1px solid ${theme.colors.borderColor}`,
    backgroundColor: theme.colors.bgCard,
    color: theme.colors.textSecondary,
    fontSize: '14px',
    fontWeight: 500,
    cursor: 'pointer',
    transition: 'all 0.2s cubic-bezier(0.23, 1, 0.32, 1)',
    whiteSpace: 'nowrap',
    outline: 'none',
  },
  buttonHover: {
    backgroundColor: theme.colors.accentLight,
    color: theme.colors.textPrimary,
    borderColor: theme.colors.accentPrimary,
    transform: 'translateY(-1px)',
    boxShadow: theme.shadows.sm,
  },
  buttonActive: {
    backgroundColor: theme.colors.accentLight,
    color: theme.colors.textPrimary,
    borderColor: theme.colors.accentPrimary,
  },
  buttonWithFilters: {
    borderColor: theme.colors.info,
    backgroundColor: theme.colors.infoLight,
    color: theme.colors.info,
  },
  badge: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: '18px',
    height: '18px',
    padding: '0 4px',
    borderRadius: '9px',
    backgroundColor: theme.colors.info,
    color: theme.colors.bgSecondary,
    fontSize: '11px',
    fontWeight: 600,
    lineHeight: 1,
  },
  overlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 999,
  },
  dropdown: {
    position: 'absolute',
    top: '100%',
    left: 0,
    marginTop: '4px',
    backgroundColor: theme.colors.bgCard,
    border: `1px solid ${theme.colors.borderColor}`,
    borderRadius: theme.radius.md,
    boxShadow: theme.shadows.lg,
    zIndex: 1000,
    overflow: 'hidden',
    minWidth: '240px',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '16px',
    borderBottom: `1px solid ${theme.colors.borderSubtle}`,
  },
  headerTitle: {
    fontSize: '14px',
    fontWeight: 600,
    color: theme.colors.textPrimary,
  },
  clearButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    padding: '4px 8px',
    border: 'none',
    borderRadius: theme.radius.sm,
    backgroundColor: 'transparent',
    color: theme.colors.textMuted,
    fontSize: '12px',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
    ':hover': {
      backgroundColor: theme.colors.accentLight,
      color: theme.colors.textPrimary,
    },
  },
  section: {
    padding: '12px 16px',
    borderBottom: `1px solid ${theme.colors.borderSubtle}`,
  },
  sectionTitle: {
    fontSize: '12px',
    fontWeight: 600,
    color: theme.colors.textMuted,
    marginBottom: '8px',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  checkboxLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '6px 0',
    cursor: 'pointer',
    transition: 'color 0.15s ease',
    ':hover': {
      color: theme.colors.textPrimary,
    },
  },
  checkbox: {
    width: '16px',
    height: '16px',
    borderRadius: '3px',
    border: `2px solid ${theme.colors.borderColor}`,
    backgroundColor: theme.colors.bgCard,
    cursor: 'pointer',
    accentColor: theme.colors.accentPrimary,
  },
  checkboxText: {
    fontSize: '14px',
    color: theme.colors.textSecondary,
    userSelect: 'none',
  },
});