import type { CSSProperties } from 'react';
import type { Theme } from '../../theme.config';

export const getFlagCardStyles = (theme: Theme, isHovered: boolean): Record<string, CSSProperties> => ({
  card: {
    backgroundColor: theme.colors.bgCard,
    border: `1px solid ${theme.colors.borderColor}`,
    borderRadius: theme.radius.lg,
    padding: '20px',
    transition: 'all 0.2s ease',
    boxShadow: isHovered ? theme.shadows.md : theme.shadows.sm,
    transform: isHovered ? 'translateY(-2px)' : 'translateY(0)',
    height: 'fit-content',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '12px',
    gap: '16px',
  },
  info: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    flex: 1,
    minWidth: 0,
  },
  nameRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  name: {
    margin: 0,
    fontSize: '15px',
    fontWeight: 600,
    color: theme.colors.textPrimary,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  key: {
    fontSize: '12px',
    color: theme.colors.textMuted,
    backgroundColor: theme.colors.bgSecondary,
    padding: '4px 8px',
    borderRadius: theme.radius.sm,
    width: 'fit-content',
    fontFamily: 'monospace',
  },
  description: {
    color: theme.colors.textSecondary,
    fontSize: '13px',
    marginBottom: '16px',
    lineHeight: 1.5,
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
  },
  actions: {
    display: 'flex',
    gap: '8px',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  menuContainer: {
    position: 'relative' as const,
  },
  menuButton: {
    padding: '8px',
    border: 'none',
    borderRadius: theme.radius.md,
    backgroundColor: 'transparent',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuOverlay: {
    position: 'fixed' as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 999,
  },
  menu: {
    position: 'absolute' as const,
    top: '100%',
    right: 0,
    marginTop: '4px',
    backgroundColor: theme.colors.bgCard,
    border: `1px solid ${theme.colors.borderColor}`,
    borderRadius: theme.radius.md,
    boxShadow: theme.shadows.lg,
    zIndex: 1000,
    minWidth: '120px',
    overflow: 'hidden',
  },
  menuItem: {
    width: '100%',
    padding: '12px 16px',
    border: 'none',
    backgroundColor: 'transparent',
    color: theme.colors.textPrimary,
    fontSize: '14px',
    fontWeight: 500,
    textAlign: 'left',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    display: 'block',
  },
  menuItemHover: {
    backgroundColor: theme.colors.bgSecondary,
  },
  menuItemDanger: {
    color: theme.colors.danger,
  },
  toggleSwitch: {
    border: 'none',
    backgroundColor: 'transparent',
    cursor: 'pointer',
    padding: '4px',
    transition: 'all 0.2s ease',
  },
  toggleTrack: {
    width: '44px',
    height: '24px',
    borderRadius: '12px',
    position: 'relative' as const,
    transition: 'all 0.2s ease',
  },
  toggleTrackOn: {
    backgroundColor: theme.colors.accentPrimary,
  },
  toggleTrackOff: {
    backgroundColor: theme.colors.bgTertiary,
    border: `1px solid ${theme.colors.borderColor}`,
  },
  toggleThumb: {
    width: '18px',
    height: '18px',
    borderRadius: '50%',
    backgroundColor: '#ffffff',
    position: 'absolute' as const,
    top: '50%',
    transform: 'translateY(-50%)',
    transition: 'all 0.2s ease',
    boxShadow: theme.shadows.sm,
  },
  toggleThumbOn: {
    left: '22px',
  },
  toggleThumbOff: {
    left: '3px',
  },

  meta: {
    display: 'flex',
    gap: '12px',
    alignItems: 'center',
    fontSize: '12px',
    color: theme.colors.textSecondary,
    flexWrap: 'wrap',
  },
  badge: {
    backgroundColor: theme.colors.accentLight,
    color: theme.colors.accentPrimary,
    padding: '4px 10px',
    borderRadius: theme.radius.md,
    fontSize: '11px',
    fontWeight: 600,
    letterSpacing: '0.3px',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
  rollout: {
    color: theme.colors.accentPrimary,
    fontWeight: 600,
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
  date: {
    marginLeft: 'auto',
    color: theme.colors.textMuted,
  },
});
