import type { CSSProperties } from 'react';
import type { Theme } from '../../theme.config';

export const getSidebarStyles = (theme: Theme, isExpanded: boolean): Record<string, CSSProperties> => ({
  sidebar: {
    width: isExpanded ? '260px' : '72px',
    backgroundColor: theme.colors.bgSecondary,
    borderRight: `1px solid ${theme.colors.borderColor}`,
    padding: '24px 0',
    flexShrink: 0,
    height: '100vh',
    position: 'sticky' as const,
    top: 0,
    display: 'flex',
    flexDirection: 'column',
    transition: 'all 0.3s cubic-bezier(0.23, 1, 0.32, 1)',
    overflow: 'hidden',
    backdropFilter: 'blur(10px)',
    boxShadow: isExpanded 
      ? theme.shadows.lg
      : theme.shadows.sm,
  },
  nav: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
    padding: isExpanded ? '0 20px' : '0 12px',
    flex: 1,
    transition: 'all 0.3s cubic-bezier(0.23, 1, 0.32, 1)',
  },
  navItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
    padding: isExpanded ? '14px 16px' : '14px 12px',
    border: 'none',
    backgroundColor: 'transparent',
    color: theme.colors.textSecondary,
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: 500,
    textAlign: 'left',
    transition: 'all 0.2s cubic-bezier(0.23, 1, 0.32, 1)',
    whiteSpace: 'nowrap',
    borderRadius: theme.radius.lg,
    width: '100%',
    justifyContent: isExpanded ? 'flex-start' : 'center',
    position: 'relative' as const,
    overflow: 'hidden',
    margin: '1px 0',
  },
  navLabel: {
    opacity: isExpanded ? 1 : 0,
    transition: 'all 0.3s cubic-bezier(0.23, 1, 0.32, 1)',
    display: isExpanded ? 'inline' : 'none',
    transform: isExpanded ? 'translateX(0)' : 'translateX(-8px)',
    letterSpacing: '-0.01em',
  },
  navItemActive: {
    backgroundColor: theme.colors.accentPrimary,
    color: theme.colors.bgSecondary,
    boxShadow: theme.shadows.md,
    transform: 'translateY(-1px)',
    fontWeight: 600,
  },
  navItemHover: {
    backgroundColor: theme.colors.accentLight,
    color: theme.colors.textPrimary,
    transform: 'translateY(-1px)',
    boxShadow: theme.shadows.sm,
  },
  bottomSection: {
    padding: isExpanded ? '20px' : '20px 12px',
    borderTop: `1px solid ${theme.colors.borderColor}`,
    marginTop: 'auto',
    transition: 'all 0.3s cubic-bezier(0.23, 1, 0.32, 1)',
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
  },
});
